---
title: "P-values, CI"
output: html_notebook
---

From Cochrane: https://www.cochranelibrary.com/cdsr/doi/10.1002/14651858.CD003823.pub2/full
Baseline systolic BP 157.1. SD of change in SBP was 13.9. Mean placebo effect -3.2. The best estimate of the near maximal blood pressure lowering (difference from placebo) for the ACE inhibitor class of drugs is -7.68 (95% CI -8.45, -6.91).
Weighted mean SD of SBP: 16.6 (table 3)

```{r setup}
library(tidyverse)
library(cowplot)
theme_set(theme_cowplot())

sbp_sd <- 16.6
effect_ace_minus_placebo <- -7.68

n_sims <- 1000

plots <- list()
widths <- list()
heights <- list()

```

P hodnoty dle velikosti efektu

```{r}
velikost_efektu <- tibble(efekt = c(0, -5 / sbp_sd, effect_ace_minus_placebo / sbp_sd, -1))
n_vzorku <- tibble(n = c(15, 30, 60, 120))
#n_vzorku <- tibble(n = seq(sqrt(15), sqrt(120), length.out = 4) ^ 2 %>% round())

single_p_sim <- function(data_row) {
  control <- rnorm(data_row$n, 0, 1)
  treatment <- rnorm(data_row$n, data_row$efekt, 1)
  test_res <- t.test(control, treatment)
  
  cbind(data_row, tibble(p = test_res$p.value, zmereny_rozdil = mean(treatment) - mean(control)))
}

p_velikost_efektu <- velikost_efektu %>% 
  crossing(n_vzorku) %>%
  crossing(sim = 1:n_sims) %>%
  transpose() %>%
  map_df(single_p_sim) %>%
  mutate(druh_rozdilu = factor(zmereny_rozdil > 0, levels = c(TRUE, FALSE), labels = c("Pozitivní", "Negativní")),
         efekt_f = factor(efekt, levels = velikost_efektu$efekt))


```



```{r}
hg_sd_label <- function(sd_val) {
  numeric_sd_val <- sd_val %>% as.numeric()
  paste0("Rozdíl: ", round(sbp_sd * numeric_sd_val, 1), " mmHg (", abs(round(numeric_sd_val, 2)), " sd)")
}


facet_efekt <- facet_wrap(~efekt_f, scales = "free_y", labeller = labeller(efekt_f = hg_sd_label))


scale_pocet <- scale_y_continuous(labels = function(x) { scales::percent(x / n_sims, accuracy = 1)}, trans = scales::trans_new("Relative", transform = function(x) { x / n_sims}, inverse = function(x) { x * n_sims}))

p_breaks <- seq(0,1, by = 0.05)
n_first_plot <- n_vzorku$n[2]

plots$p_fixini_n_prvni <- p_velikost_efektu %>% filter(n == n_first_plot) %>% 
  ggplot(aes(x = p, alpha = p < 0.05)) + geom_histogram(breaks = p_breaks) +  
  scale_alpha_discrete(range = c(0.5,1), guide = FALSE) +
  scale_pocet + facet_efekt + ggtitle(paste0("N: ", n_first_plot))
plots$p_fixini_n_prvni

for(n_k_zobrazeni in n_vzorku$n) {
  plot_name <- paste0("p_fixni_n_", n_k_zobrazeni)
  plots[[plot_name]] <- p_velikost_efektu %>% filter(n == n_k_zobrazeni) %>% ggplot(aes(x = p, fill = druh_rozdilu, alpha = p < 0.05)) + geom_histogram(breaks = p_breaks) + 
      scale_pocet + facet_efekt + scale_fill_discrete("Změřený rozdíl") +
      scale_alpha_discrete(range = c(0.5,1), guide = FALSE) +
      ggtitle(paste0("N: ", n_k_zobrazeni))
  print(plots[[plot_name]])
}


for(efekt_k_zobrazeni in velikost_efektu$efekt) {
  plot_name <- paste0("p_fixni_efekt_", round(efekt_k_zobrazeni,2))
  plots[[plot_name]] <- p_velikost_efektu %>% filter(efekt == efekt_k_zobrazeni) %>% ggplot(aes(x = p, fill = druh_rozdilu, alpha = p < 0.05)) + 
      geom_histogram(breaks = p_breaks) + facet_wrap(~n, labeller = label_both, scales = "free_y") + 
      scale_fill_discrete("Změřený rozdíl") + scale_pocet +
      scale_alpha_discrete(range = c(0.5,1), guide = FALSE) +
      ggtitle(hg_sd_label(efekt_k_zobrazeni))
  print(plots[[plot_name]])
}


```

```{r}
power.t.test(delta = effect_ace_minus_placebo, sd = sbp_sd, sig.level = 0.05, power = 0.8)
```

```{r}
efekty <- velikost_efektu$efekt[c(2,3)]
nka <- n_vzorku$n[c(2,4)]
for(i in 1:length(efekty) ) {
  n_k_zobrazeni <- nka[i]
  efekt_k_zobrazeni <- efekty[i]
  plot_name <- paste0("m_and_s_error_",n_k_zobrazeni,"_eff_", round(abs(efekt_k_zobrazeni),2))
  plots[[plot_name]] <- p_velikost_efektu %>% filter(n == n_k_zobrazeni, efekt == efekt_k_zobrazeni, p < 0.05) %>%
    ggplot(aes(x = zmereny_rozdil * sbp_sd)) + geom_histogram(aes(y = stat(width*density)), binwidth = 1)  + geom_vline(xintercept = efekt_k_zobrazeni * sbp_sd, color = "blue", size = 2, linetype = "dashed") + 
    facet_efekt + scale_y_continuous("Podíl", labels = scales::percent) + scale_x_continuous("Změřený rozdíl [mmHg]") +
    ggtitle(paste0("Pouze p < 0.05, N: ", n_k_zobrazeni))
  print(plots[[plot_name]])
  
  widths[[plot_name]] <- 6
}
```


# Více studií

```{r}
n_studii <- 8
n_vice_studii <- 30
studie_df_raw <- list()
next_id <- 1
efekty_pro_vice_studii <- c(0, velikost_efektu$efekt[3])
for(efekt_pro_simulace in efekty_pro_vice_studii) {
  p_pro_sim <- p_velikost_efektu %>% filter(n == n_vice_studii, efekt == efekt_pro_simulace)
  for(i in 1:n_sims) {
    studie_df_raw[[next_id]] <- p_pro_sim %>% sample_n(n_studii) %>% 
      group_by(n, efekt, efekt_f) %>%
      summarise(min.p = min(p), max.p = max(p), min.zmereny_rozdil = min(zmereny_rozdil), max.zmereny_rozdil = max(zmereny_rozdil))
      #summarise(min.p = min(p), max.p = max(p), min.zmereny_rozdil = min(c(Inf,zmereny_rozdil[p < 0.05])), max.zmereny_rozdil = max(c(-Inf,zmereny_rozdil[p < 0.05])))
    next_id <- next_id + 1
  }
}

p_vice_studii <- do.call(rbind, studie_df_raw)

p_vice_studii_long <- p_vice_studii %>%
      pivot_longer(c("min.p","max.p","min.zmereny_rozdil","max.zmereny_rozdil"), names_to = c("typ","meritko"), names_sep = "\\.", values_to = "hodnota") 

```

```{r}
for(efekt_k_zobrazeni in efekty_pro_vice_studii) {
  plot_name_base <- paste0("vice_studii_", abs(round(efekt_k_zobrazeni,2)),"_")
  title <- ggtitle(paste0(n_studii, " studií, N: ", n_vice_studii))
  
  plot_name_p <- paste0(plot_name_base, "_p")
  plots[[plot_name_p]] <- p_vice_studii_long %>% filter(meritko == "p", efekt == efekt_k_zobrazeni) %>%
      ggplot(aes(x = hodnota, color = typ)) + geom_freqpoly(breaks = p_breaks) + scale_pocet + facet_efekt + title +
      geom_vline(xintercept = 0.05, color = "green", size = 2, linetype = "dashed") +
    scale_x_continuous("p-hodnota")
  widths[[plot_name_p]] <- 6
  print(plots[[plot_name_p]])

  plot_name_zmereny <- paste0(plot_name_base, "_zmereny_rozdil")
  plots[[plot_name_zmereny]] <- p_vice_studii_long %>% filter(meritko == "zmereny_rozdil", efekt == efekt_k_zobrazeni, !is.infinite(hodnota)) %>%
      ggplot(aes(x = hodnota * sbp_sd, color = typ)) + geom_freqpoly(bins = 10) + scale_pocet + facet_efekt + title +
    geom_vline(xintercept = efekt_k_zobrazeni * sbp_sd, color = "blue", size = 2, linetype = "dashed") +
    scale_x_continuous("Změřený rozdíl")
  widths[[plot_name_zmereny]] <- 6
  print(plots[[plot_name_zmereny]])
  
}
```



TODO radeji fakt simulovat RCT (dve skupiny)

```{r}
full_population <- rnorm(1e6, effect_ace_minus_placebo, sbp_sd)
increase_biases <- c(3/2, 4/3, 11/10)

biased_study_population_size <- 1e5
biased_study_errors <- numeric(n_sims * length(increase_biases))
for(bias in increase_biases) {
  full_population_probs <-if_else(full_population < 0, 1, bias)
  for(i in 1:n_sims) {
    biased_sample <- sample(full_population, size = biased_study_population_size, replace = TRUE, prob = full_population_probs)
    biased_study_errors[i] <- (mean(biased_sample) - effect_ace_minus_placebo)^2 
  }
}
  
rct_results <- data.frame(sample_size = 5 * (2 ^ (0:7))) %>% crossing(sim = 1:n_sims) %>%
  rowwise() %>%
  mutate(error = mean(rnorm(sample_size, 0, sbp_sd)) ^ 2) %>%
  group_by(sample_size) %>%
  summarise(low_error = sqrt(quantile(error, 0.025)), mean_error = sqrt(mean(error)), high_error = sqrt(quantile(error, 0.975)))

biased_results <- data.frame(low_error = sqrt(quantile(biased_study_errors, 0.025)), mean_error = sqrt(mean(biased_study_errors)), high_error = sqrt(quantile(biased_study_errors, 0.975))) %>% 
  crossing(data.frame(sample_size = unique(rct_results$sample_size)))


```

```{r}
plots$rct_error <- 
rct_results %>% ggplot(aes(x = sample_size, y = mean_error))  + #, ymin = low_error, ymax = high_error
  #geom_ribbon(alpha = 0.3) + 
  geom_line() + 
#  geom_ribbon(data = biased_results, fill = "blue", alpha = 0.3) + 
  scale_y_continuous("Půměrná chyba RCT [mmHg]") +
  scale_x_continuous("Velikost vzorku RCT")

hline_size <- 2
pal <- viridisLite::plasma(3)

plots$rct_error_biased <- 
  plots$rct_error +
    geom_hline(data = biased_results, aes(yintercept = mean_error), color = pal[2], size = hline_size)

plots$rct_error_biased_decoy <- 
  plots$rct_error_biased +
    geom_hline(yintercept = 0.84, color =  pal[1], size = hline_size) +
    geom_hline(yintercept = 2.53, color =  pal[3], size = hline_size)

```

Láme se to u cca 80 pacientů v RCT

```{r, fig.width= 6, fig.height=5}
set.seed(56852266)
data_pohledny <- data.frame(pohledny = rnorm(200), laskavy = rnorm(200))

plot_pohledny <- function(split = "none", trend = FALSE) {
  
  if(split == "none") {
    data_to_plot <- data_pohledny %>% mutate(group = 1)
    alpha_scale = scale_alpha_continuous(range = c(0.999, 1), guide = FALSE)
  } else {
    alpha_scale <- scale_alpha_continuous(range = c(0.2, 1), guide = FALSE)
    if (split == "up") {
      data_to_plot <- data_pohledny %>% mutate(group = if_else(pohledny + laskavy > 0, 1, 0))
    } else if (split == "down") {
      data_to_plot <- data_pohledny %>% mutate(group = if_else(pohledny + laskavy < 0, 1, 0))
    }
  }
  
  if(trend) {
  #  smooth <- geom_smooth(aes(x = pohledny, y = laskavy), inherit.aes = FALSE, data = rbind(data_to_plot %>% filter(group > 0), data.frame(laskavy = 0, pohledny = 0, group = 0)), method = "lm", formula = y ~x)
    smooth <- geom_smooth(aes(x = pohledny, y = laskavy), inherit.aes = FALSE, data = data_to_plot %>% filter(group > 0), method = "lm", formula = y ~x)
  } else {
    smooth <- NULL
  }
  data_to_plot %>% 
    ggplot(aes(x = pohledny, y = laskavy, alpha = group)) + 
    scale_x_continuous("Pohledný", breaks = c(-1.5, 1.5), labels = c("Málo", "Hodně")) + scale_y_continuous("Laskavý", breaks = c(-1.5, 1.5), labels = c("Málo", "Hodně"))+ 
    geom_vline(xintercept = 0) + geom_hline(yintercept =  0) + 
    geom_point(color = viridisLite::plasma(3)[2]) +
    smooth +
    alpha_scale +
    theme(axis.line = element_blank(), axis.ticks = element_blank())
}

plots$laskavy_pohledny_1 <- plot_pohledny("none")
plots$laskavy_pohledny_2 <- plot_pohledny("none", TRUE)
plots$laskavy_pohledny_3 <- plot_pohledny("up")
plots$laskavy_pohledny_4 <- plot_pohledny("up", TRUE)   
plots$laskavy_pohledny_5 <- plot_pohledny("down")
plots$laskavy_pohledny_6 <- plot_pohledny("down", TRUE)
for(plot_name in paste0("laskavy_pohledny_", 1:6)){
  print(plots[[plot_name]])
  widths[[plot_name]] <- 6
  heights[[plot_name]] <- 5
}
```

```{r}
set.seed(99852665)
n_obs <- 100
data_regression_to_the_mean <- data.frame(id = 1:n_obs, before = rnorm(n_obs, mean = 30, sd = 2), after = rnorm(n_obs, mean = 30, sd = 2)) %>% mutate(selected = as.numeric(before > 32), improved = before > after) %>%
  pivot_longer(c("before", "after"),names_to = "group", values_to = "BMI") %>%
  mutate(group = factor(group, levels = c("before","after")))

data_regression_to_the_mean %>% ggplot(aes(x = group,y = BMI, alpha = selected, color = improved, group = id)) + geom_line() + geom_point() + scale_alpha(range = c(0.2, 1), guide = FALSE) 

```


```{r}
tmp_dir <- here::here("local_tmp_data")
if(!dir.exists(tmp_dir)) {
  dir.create(tmp_dir)
}

for(plot_name in names(plots)) {
  if(!is.null(widths[[plot_name]])) {
    width <- widths[[plot_name]]
  } else {
    width <- 8
  }
  if(!is.null(heights[[plot_name]])) {
    height <- heights[[plot_name]]
  } else {
    height <- width * 0.6666666666667
  }
  ggsave(plot = plots[[plot_name]], filename = paste0(tmp_dir,"/",plot_name,".png"), dpi = 300, width = width, height = height)
}
```
